apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: week1
type: Opaque
stringData:
  OIDC_CLIENT_ID: "YOUR_CLIENT_ID"
  OIDC_CLIENT_SECRET: "YOUR_CLIENT_SECRET"
  OIDC_ISSUER: "https://id-dev.mindx.edu.vn"
  SESSION_SECRET: "YOUR_RANDOM_LONG_SECRET"
  FRONTEND_URL: "https://<IP_OR_DOMAIN>"
  OIDC_REDIRECT_URI: "https://<IP_OR_DOMAIN>/auth/callback"
